ActivitiesList = [
    'Yoga',
    'Pilates',
    'Gym',
    'Spinning',
    'Bowling',
    'Table Tennis',
    'Squash',
    'Bouldering',
    'Dance',
    'Gymnastics',
    'Zumba',
    'Indoor Cycling',
    'Jump Rope',
    'Kickboxing',
    'Aerobics',
    'Handball',
    'Basketball',
    'Badminton',
    "Running",
    "Cycling",
    "Hiking",
    "Volleyball",
    "Kayaking",
    "Skating",
    "Dragon Boating",
    "Outdoor Yoga",
    "Soccer",
    "Snowboarding",
    "Tennis",
    "Rollerblading",
    "Wakeboarding",
    "Fishing",
    "Basketball",
    "Archery",
    "Windsurfing",
    "Trail Running",
    "Frisbee",
    "Kite Flying"
]